### ISSUE TITLE
NullPointerException when importing app

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#122]
When importing the "cn.wps.moffice_eng.apk" file from the Play Store, CodeInspect throws a NullPointerException
![npe](https://cloud.githubusercontent.com/assets/2691304/7315567/e4e0bdba-ea6e-11e4-85f1-59046ca308be.png)
.

**Comment by StevenArzt** [comment]
After confirming the NPE, CodeInspect tries to delete the already-existing parts of the project and arrives at another exception.
![exception](https://cloud.githubusercontent.com/assets/2691304/7315582/130ba0b0-ea6f-11e4-978a-82f006347839.png)

**Comment by marcellmajor** [comment]
When loading an obfuscated JAR

![nullpointer](https://cloud.githubusercontent.com/assets/4268602/8526897/c4009780-2409-11e5-846f-e3f8da3d0a52.png)

**Comment by MarcMil** [comment]
@marcellmajor Thanks for reporting - this bug should be fixed by now. The new build is already on the server.

Please note that debugging Code imported from JAR files is not implemented yet.

**Comment by StevenArzt** [comment]
This problem still occurs with the most recent version of CodeInspect.

**Comment by StevenArzt** [comment]
We now have a different error message.
![issue](https://cloud.githubusercontent.com/assets/2691304/9790994/3ec7b40a-57d9-11e5-95ba-bee432bf772a.png)

**Comment by StevenArzt** [comment]
After confirming that error message, we still get the NPE
![npe](https://cloud.githubusercontent.com/assets/2691304/9791009/5cfd911a-57d9-11e5-9d70-f32c07276292.png)

**Comment by MarcMil** [comment]
Alright, problem with Windows and its reserved file names... Should be fixed by now, the next nightly build will contain the fix.

**Comment by StevenArzt** [comment]
Importing now seems to with. The test machine runs out of memory, but that's a different problem.
