### ISSUE TITLE
Licensing dialog appears multiple times

### ISSUE THREAD

**Issue by StevenArzt** [secure-software-engineering/CodeInspect#179]
If a computer running CodeInspect is put to sleep and then resumed, it displays an error message stating that the license server cannot be contacted (simply because the network is not yet up again). If the user waits a little, confirms with "ok", refreshes the license list (which then shows "active"), and clicks "ok" again, he would assume that he can continue working. The dialog, however, shows again. The process must be repeated several times before the user can continue working with CodeInspect.

**Comment by MarcMil** [comment]
Should be fixed now.

**Comment by StevenArzt** [comment]
The window still appears twice (at least not more often than twice now) with the current version.

**Comment by StevenArzt** [comment]
Appears to be really fixed now.
